### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by pwichmann** [BachiLi/diffvg#19]
Many thanks for this amazing repo!

Unfortunately, I was unable to build diffvg.
I am not an expert (in anything) -- are you able to understand what went wrong from the error message below?

### Environment

- Ubuntu 20.04
- Python 3.9.2
- Conda environment

### Error log

```
python setup.py build --debug install
running build
running build_py
running build_ext
CMake Error at CMakeLists.txt:13 (add_subdirectory):
  The source directory

    /home/user/Documents/01_quiv/09_diffvg/diffvg/pybind11

  does not contain a CMakeLists.txt file.


-- Build with CUDA support
INFO Building without TensorFlow support (not found)
-- Configuring incomplete, errors occurred!
See also "/home/user/Documents/01_quiv/09_diffvg/diffvg/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeOutput.log".
See also "/home/user/Documents/01_quiv/09_diffvg/diffvg/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/user/Documents/01_quiv/09_diffvg/diffvg/setup.py", line 91, in <module>
    setup(name = 'diffvg',
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/Documents/01_quiv/09_diffvg/diffvg/setup.py", line 31, in run
    super().run()
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/Documents/01_quiv/09_diffvg/diffvg/setup.py", line 64, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/user/anaconda3/envs/im2vec/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/user/Documents/01_quiv/09_diffvg/diffvg', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/user/Documents/01_quiv/09_diffvg/diffvg/build/lib.linux-x86_64-3.9', '-DPYTHON_INCLUDE_PATH=/home/user/anaconda3/envs/im2vec/include/python3.9', '-DCMAKE_BUILD_TYPE=Debug', '-DDIFFVG_CUDA=1']' returned non-zero exit status 1.
```

**Comment by pwichmann** [comment]
Solved by re-installing parts of CUDA.

**Comment by Actasidiot** [comment]
> Solved by re-installing parts of CUDA.

Hi, could you share some more details? I have the same problem.

**Comment by Yuxinn-J** [comment]
Hii, I encountered the same issue as well. Did anyone solve this? Thank you!!!!

**Comment by yizhiwang96** [comment]
> Hii, I encountered the same issue as well. Did anyone solve this? Thank you!!!!

Hi Yuxinn. I forget the details but I worked for me by re-installing. First, I built a **python 3.9 + pytorch 1.9 conda** environment. Then, in this environment, I run "git clone https://github.com/BachiLi/diffvg --recursive" make sure **no network issues**. Then following the other install instructions.
