### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by Speido** [BachiLi/diffvg#6]
The library compiles without errors under Windows (Windows 10, Python 3.8, torch 1.6, VS2019). However, running examples results in:
`python single_circle.py
Traceback (most recent call last):
  File "single_circle.py", line 1, in <module>
    import pydiffvg
  File "C:\conda\envs\NR\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg\__init__.py", line 4, in <module>
    from .render_pytorch import *
  File "C:\conda\envs\NR\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg\render_pytorch.py", line 18, in <module>
    class RenderFunction(torch.autograd.Function):
  File "C:\conda\envs\NR\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg\render_pytorch.py", line 27, in RenderFunction
    filter = pydiffvg.PixelFilter(type = diffvg.FilterType.box,
AttributeError: module 'diffvg' has no attribute 'FilterType'`

`dir(diffvg)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`

Any advice?

**Comment by BachiLi** [comment]
Most likely you didn't install the module properly. Have you run `python setup.py install` in the corresponding conda environment?

**Comment by xieMNll** [comment]
I met the same error.    
__AttributeError: module 'diffvg' has no attribute 'FilterType_'_

I git clone the code, and pip install all requirements. Then I run _python setup.py install_ .

_Using c:\programdata\anaconda3\envs\torch\lib\site-packages
Finished processing dependencies for diffvg==0.0.1_

But it showed  ModuleNotFoundError: No module named 'diffvg'. So I copied all diffvg project in my conda environment site_packages.  when import pydiffvg, the error occured: 
  File "single_circle.py", line 2, in <module>
    import pydiffvg
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\diffvg-0.0.1-py3.7-win-amd64.egg\pydiffvg\__init__.py", line 4, in <module>
    from .render_pytorch import *
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\diffvg-0.0.1-py3.7-win-amd64.egg\pydiffvg\render_pytorch.py", line 21, in <module>
    class RenderFunction(torch.autograd.Function):
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\diffvg-0.0.1-py3.7-win-amd64.egg\pydiffvg\render_pytorch.py", line 30, in RenderFunction
    filter=pydiffvg.PixelFilter(type=diffvg.FilterType.box,
AttributeError: module 'diffvg' has no attribute 'FilterType'

**Comment by APX403** [comment]
Same problem on my windows install

**Comment by d00ML0rDz** [comment]
Renaming the site-packages/diffvg-0.0.1-py3.8-win-amd64.egg/diffvg file to diffvg.pyd seems to have fixed this for me.

**Comment by IzhanVarsky** [comment]
> Renaming the site-packages/diffvg-0.0.1-py3.8-win-amd64.egg/diffvg file to diffvg.pyd seems to have fixed this for me.

Hi, thank you! This helped me to solve the problem "ModuleNotFoundError: No module named 'diffvg'" in "pydiffvg\render_pytorch.py" file. I used win10 with pip.

**Comment by lemonholic** [comment]
> Renaming the site-packages/diffvg-0.0.1-py3.8-win-amd64.egg/diffvg file to diffvg.pyd seems to have fixed this for me.

Thanks a lot! I used conda + win10, encountered the same issue as @IzhanVarsky did, and resolved it thanks to your help.
