### ISSUE TITLE
Unable to open file "python310.lib"

### ISSUE THREAD

**Issue by yuridb98** [BachiLi/diffvg#74]
I get the following error when i execute "python setup.py install":

LINK : fatal error LNK1104: impossibile aprire il file 'python310.lib' [C:\Users\dibiasiy\Desktop\im2vec\diffvg\build\t
emp.win-amd64-cpython-310\Debug\diffvg.vcxproj]

And then:

Traceback (most recent call last):
  File "C:\Users\dibiasiy\Desktop\im2vec\diffvg\setup.py", line 92, in <module>
    setup(name = 'diffvg',
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\dibiasiy\Desktop\im2vec\diffvg\setup.py", line 31, in run
    super().run()
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\dibiasiy\Desktop\im2vec\diffvg\setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "C:\Users\dibiasiy\AppData\Local\anaconda3\envs\venv\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Debug', '--', '/m']' returned non-zero exit status 1.

Trying to install it on conda venv with python 3.10.11

**Comment by kepurG** [comment]
I spent days and nights to complete the diffvg compilation on Windows. If anyone wants the wheels, you can contact me +V13862010554. Let's create a group to communicate and exchange about the improvements based on the module together.

**Comment by Zysun2002** [comment]
I encountered the same issue. Have you solved it?
