### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by RomanticGodVAN** [BachiLi/diffvg#77]
copy the issue like：
CMake Error at /usr/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/bin/cmake/share/cmake-3.26/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:33 (find_package)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/home/dachuang/map/diffvg/setup.py", line 92, in <module>
    setup(name = 'diffvg',
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dachuang/map/diffvg/setup.py", line 31, in run
    super().run()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/dachuang/map/diffvg/setup.py", line 65, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/dachuang/anaconda3/envs/diffvg/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/dachuang/map/diffvg', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/dachuang/map/diffvg/build/lib.linux-x86_64-cpython-39', '-DPYTHON_LIBRARY=/hom
e/dachuang/anaconda3/envs/diffvg/lib', '-DPYTHON_INCLUDE_PATH=/home/dachuang/anaconda3/envs/diffvg/include/python3.9', '-DCMAKE_BUILD_TYPE=Release', '-DDIFFVG_CUDA=0']' returned non-zero exit statu
s 1.

**Comment by CodeGeek04** [comment]
i got same issue on ubuntu

**Comment by Yi-Lynn** [comment]
Hi, I met the same problem, have you solved it yet? Thanks!!

**Comment by CodeGeek04** [comment]
In my case, there were some issues with cmake. I got some warnings, and I focused on solving them first. Once I fixed all warnings, the library got installed without any issues

**Comment by Yi-Lynn** [comment]
> In my case, there were some issues with cmake. I got some warnings, and I focused on solving them first. Once I fixed all warnings, the library got installed without any issues

@CodeGeek04 Hi, May I ask what warnings you got and how you solved them? I'd really appreciate it if you could provide any details.

**Comment by CodeGeek04** [comment]
If you are getting the same exact error, then their might be a warning just above the Trace Stack. On time it was regarding nvidia cuda toolkit incompatibility, so I had to reinstall it. I dont remember other warnings. However if you see any such issues, above trace stack, you can share them here and I'll try to remember the soution

**Comment by Yi-Lynn** [comment]
> If you are getting the same exact error, then their might be a warning just above the Trace Stack. On time it was regarding nvidia cuda toolkit incompatibility, so I had to reinstall it. I dont remember other warnings. However if you see any such issues, above trace stack, you can share them here and I'll try to remember the soution

Thank you @CodeGeek04. I had the same issue as @RomanticGodVAN, related to the PYTHONLIB not being found, as shown below. Fortunately, I just solved this problem by cleaning and deleting the whole diffvg folder from my project and git clone it again.
```
CMake Error at /usr/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
/usr/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
/usr/bin/cmake/share/cmake-3.26/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:33 (find_package)
```

Many thanks to your kind reply :)

**Comment by kepurG** [comment]
I spent days and nights to complete the diffvg compilation on Windows. If anyone wants the wheels, you can contact me +V13862010554. Let's create a group to communicate and exchange about the improvements based on the module together.

**Comment by benbaker76** [comment]
You can check out my [fork](https://github.com/benbaker76/diffvg) which has instructions on how to create the wheel and install on Windows.

**Comment by Sapf3ar** [comment]
Just add the following line to the setup.py script: 
https://github.com/BachiLi/diffvg/blob/85802a71fbcc72d79cb75716eb4da4392fd09532/setup.py#L38-L40
  ```python
 cmake_args = ['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=' + extdir,
                          '-DPYTHON_LIBRARY=' + get_config_var('LIBDIR'),
                          '-DPYTHON_INCLUDE_PATH=' + include_path, #   <--- here
                          '-DPYTHON_INCLUDE_DIR=' + include_path]
```
