### ISSUE TITLE
Could someone build a WHL for Windows CUDA 11.8?

### ISSUE THREAD

**Issue by SoftologyPro** [BachiLi/diffvg#80]
If anyone is able to build under Windows can you please share a WHL?
ie `python setup.py sdist bdist_wheel`

**Comment by SoftologyPro** [comment]
WHL now here.
https://huggingface.co/Nekochu/Models/blob/main/diffvg_whl_torch_118/releases/diffvg-0.0.1-cp310-cp310-win_amd64.whl

But when installed and running the script I get
```
Traceback (most recent call last):
  File "D:\Tests\Dynamic Typography\dynamicTypography.py", line 1, in <module>
    from painter_dTypo import Painter, PainterOptimizer
  File "D:\Tests\Dynamic Typography\painter_dTypo.py", line 10, in <module>
    import pydiffvg
  File "D:\Tests\Dynamic Typography\venv\lib\site-packages\pydiffvg\__init__.py", line 4, in <module>
    from .render_pytorch import *
  File "D:\Tests\Dynamic Typography\venv\lib\site-packages\pydiffvg\render_pytorch.py", line 18, in <module>
    class RenderFunction(torch.autograd.Function):
  File "D:\Tests\Dynamic Typography\venv\lib\site-packages\pydiffvg\render_pytorch.py", line 27, in RenderFunction
    filter = pydiffvg.PixelFilter(type = diffvg.FilterType.box,
```

This issue https://github.com/BachiLi/diffvg/issues/27#issuecomment-1048905132 says to rename the file, but that file/directory does not exist on Windows (or at least not here once I install the WHL).

**Comment by kepurG** [comment]
I spent days and nights to complete the diffvg compilation on Windows. If anyone wants the wheels, you can contact me +V13862010554. Let's create a group to communicate and exchange about the improvements based on the module together.

**Comment by SoftologyPro** [comment]
> I spent days and nights to complete the diffvg compilation on Windows. If anyone wants the wheels, you can contact me +V13862010554. Let's create a group to communicate and exchange about the improvements based on the module together.

There is already a whl above for anyone who needs it.
Does your wheel correctly work with the script and not give the error I encountered above?
If so, please share it on Hugging Face ir any other host so I can try it.

**Comment by benbaker76** [comment]
You can check out my [fork](https://github.com/benbaker76/diffvg) which has instructions on how to create the wheel and install on Windows.
