### ISSUE TITLE
Upon cloning onto my machine

### ISSUE THREAD

**Issue by LeeTaylorLondon** [BachiLi/diffvg#83]
Obtaining file:///C:/Users/lees_/PycharmProjects/diffvg
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Collecting pygame<3.0.0,>=2.0.1 (from diffvg==0.1.0)
  Obtaining dependency information for pygame<3.0.0,>=2.0.1 from https://files.pythonhosted.org/packages/07/ef/da1c0efe66d15c11138e4e2b616e2fb3d027c4cbf7cd325c0f961671ea88/pygame-2.6.0-cp310-cp310-win_amd64.whl.metadata
  Downloading pygame-2.6.0-cp310-cp310-win_amd64.whl.metadata (13 kB)
Downloading pygame-2.6.0-cp310-cp310-win_amd64.whl (10.7 MB)
   ---------------------------------------- 10.7/10.7 MB 81.8 MB/s eta 0:00:00
Building wheels for collected packages: diffvg
  Building editable for diffvg (pyproject.toml): started
  Building editable for diffvg (pyproject.toml): finished with status 'error'
Failed to build diffvg

  error: subprocess-exited-with-error
  
  Building editable for diffvg (pyproject.toml) did not run successfully.
  exit code: 1
  
  [22 lines of output]
  Traceback (most recent call last):
    File "C:\Users\lees_\PycharmProjects\diffvg\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\lees_\PycharmProjects\diffvg\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\lees_\PycharmProjects\diffvg\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 273, in build_editable
      return hook(wheel_directory, config_settings, metadata_directory)
    File "C:\Users\lees_\AppData\Local\Temp\pip-build-env-kjnx50ng\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 82, in build_editable
      return WheelBuilder.make_in(
    File "C:\Users\lees_\AppData\Local\Temp\pip-build-env-kjnx50ng\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
      wb.build(target_dir=directory)
    File "C:\Users\lees_\AppData\Local\Temp\pip-build-env-kjnx50ng\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 118, in build
      self._add_pth(zip_file)
    File "C:\Users\lees_\AppData\Local\Temp\pip-build-env-kjnx50ng\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 147, in _add_pth
      for include in self._module.includes:
    File "C:\Users\lees_\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
      val = self.func(instance)
    File "C:\Users\lees_\AppData\Local\Temp\pip-build-env-kjnx50ng\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 97, in _module
      return Module(
    File "C:\Users\lees_\AppData\Local\Temp\pip-build-env-kjnx50ng\overlay\Lib\site-packages\poetry\core\masonry\utils\module.py", line 65, in __init__
      raise ModuleOrPackageNotFound(
  poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package diffvg
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for diffvg
ERROR: Could not build wheels for diffvg, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by Goulustis** [comment]
I saw this when I'm installing with pip. You just need to move project.tml out of the directory so pip will use setup.py instead.
